all:
	gcc -Wall -ggdb -o list list.c `pkg-config --cflags glib-2.0` `pkg-config --libs glib-2.0`
	g++ -Wall -ggdb -o frases frases.cpp `pkg-config --cflags glib-2.0` `pkg-config --libs glib-2.0`
#	gcc -Wall -ggdb -o a a.cpp `pkg-config --cflags glib-2.0` `pkg-config --libs glib-2.0`
